name: Generate ChangeLog

on:
  workflow_dispatch:
    inputs:
      lastVersion:
        description: "Last Version"
        required: true
        default: '1.0.0'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
    - name: Install github changelog generator
      run: |
        gem install github_changelog_generator
